### ISSUE TITLE
Merge Conflict Head trail needs to be removed from Documentation route

### ISSUE THREAD

**Issue by piyush97** [reactjs/hi.reactjs.org#113]
## Issue 
* Merge Conflict Head trail needs to be removed from Documentation route
* Link: https://hireactjsorg.fbopensource.vercel.app/tutorial/tutorial.html#inspecting-the-starter-code
![image](https://user-images.githubusercontent.com/18229627/105456684-9aba5d80-5cab-11eb-9574-52cc52f8221b.png)

**Comment by arshadkazmi42** [comment]
This seems to be fixed now in main branch
