### ISSUE TITLE
Starter code from CodeSandbox not loading in Production (Current) release

### ISSUE THREAD

**Issue by piyush97** [reactjs/hi.reactjs.org#114]
Starter code from CodeSandbox not loading in Production (Current) release

Link: https://hireactjsorg.fbopensource.vercel.app/tutorial/tutorial.html#inspecting-the-starter-code
![image](https://user-images.githubusercontent.com/18229627/105456855-e5d47080-5cab-11eb-949a-3660a3210a4b.png)

**Comment by arshadkazmi42** [comment]
This seems to be fixed. In latest main branch

https://hireactjsorg-fbopensource.vercel.app/tutorial/tutorial.html#inspecting-the-starter-code
