### ISSUE TITLE
I have a query regarding translation ( I am new here )

### ISSUE THREAD

**Issue by Akshit1025** [reactjs/hi.reactjs.org#183]
So hey,
I am Akshit and I am from India
I want to help you guys by translating the website to a Hindi website 
so I wanted to ask how is it done and what all has to be done because I am not able to understand the process given in the README.md file, so can anyone explain me what all do we have to do exactly

**Comment by arshadkazmi42** [comment]
Hi @Akshit1025 

We are in process of translating only beta pages now. You can get more details in this Issue https://github.com/reactjs/hi.reactjs.org/issues/168

Also, you should refer these two tickets for glossary (details about common words and the words which we are not translation) https://github.com/reactjs/hi.reactjs.org/issues/2

To know more about the review process refer this #23 

Let me know if you need any other info.

**Comment by Akshit1025** [comment]
thanks for the quick reply. I look into these
thanks

**Comment by Akshit1025** [comment]
> Hi @Akshit1025
> 
> We are in process of translating only beta pages now. You can get more details in this Issue #168
> 
> Also, you should refer these two tickets for glossary (details about common words and the words which we are not translation) #2
> 
> To know more about the review process refer this #23
> 
> Let me know if you need any other info.

hey I wanted to ask that after translating the page
what all has to be done (frankly speaking I will be doing my first pull request when finished)
so that is why I am asking what all has to be done after the translation of the pages

**Comment by arshadkazmi42** [comment]
@Akshit1025 

You can do following

1. Fork the repository
2. Clone the forked repository
3. Do the translation
4. Check in the translated file.
5. Navigate to this repo, you will see an option to create pull request. 
For more info you can check this repository https://github.com/firstcontributions/first-contributions

**Comment by Akshit1025** [comment]
> @Akshit1025
> 
> You can do following
> 
> 1. Fork the repository
> 2. Clone the forked repository
> 3. Do the translation
> 4. Check in the translated file.
> 5. Navigate to this repo, you will see an option to create pull request.
>    For more info you can check this repository https://github.com/firstcontributions/first-contributions

ok thanks
