### ISSUE TITLE
Wrong Translation on Homepage in Hindi

### ISSUE THREAD

**Issue by arpitbatra123** [reactjs/hi.reactjs.org#20]
The homepage of the reactjs project in the `Hindi` Language has a translation that is not proper.
On, https://hi.reactjs.org/ ,
![image](https://user-images.githubusercontent.com/21967563/53492872-e9f7b380-3abf-11e9-878f-132e6fa69eca.png)
It says ` React Native का उपयोग करके पावर मोबाइल ऐप भी बना सकते हैं।` which is a wrong translation of the same text on the english version that says `and power mobile apps using React Native.` It can be simply translated to `React Native का उपयोग करके मोबाइल एप्प्स भी बना सकते हैं।`. Will be happy to send a PR for this if you all also feel that this issue warrants attention.

**Comment by arshadkazmi42** [comment]
> english version that says `and power mobile apps using React Native.`

What does power means in this context?

**Comment by arpitbatra123** [comment]
`power` in the context of `power mobile apps` means providing mobile applications the necessary capabilities to run.

**Comment by arshadkazmi42** [comment]
Then isn't it suppose to mean similar in hindi too? As the direct hindi translation of this would be `बिजली मोबाइल एप्लिकेशन` I think due to this only we have not translated the words and just changed the spelling in hindi.

Also we have alot of pages pending to be translated in hindi. If you would like to contribute then do have a look at #1

**Comment by arpitbatra123** [comment]
Yes it is supposed to mean similar, but currently if we translate the Hindi text back to english, it would mean `you can create power mobile apps` which makes no sense. Since there's no meaningful direct translation, `React Native का उपयोग करके मोबाइल एप्प्स भी बना सकते हैं।` can be used which will simply mean `You can also create mobile apps using React Native`. And Sure, If I get time, I will contribute to the ongoing translation.

**Comment by arpitbatra123** [comment]
Also, i can see that the homepage translation is marked as done, but in many places the translation has only been done literally and makes no sense after translation. Such as `Learn Once, Write Anywhere` should have been translated to `एक बार सीखे` instead of `एक बार जानें `.  Can I have another go at the homepage and fix these translations?

**Comment by arpitbatra123** [comment]
Also, i can see that the homepage translation is marked as done, but in many places the translation has only been done literally and makes no sense after translation. Such as `Learn Once, Write Anywhere` should have been translated to `एक बार सीखे` instead of `एक बार जानें `.  Can I have another go at the homepage and fix these translations?

**Comment by saranshkataria** [comment]
@arpitbatra123 you could do that, or can we have everything translated first and then go over such instances? Would be better to have something up first and then we can revisit them?

**Comment by saranshkataria** [comment]
Closing this out.
