### ISSUE TITLE
React js in Hindi Language

### ISSUE THREAD

**Issue by Sandeepkumarmadhdeshiya** [reactjs/hi.reactjs.org#215]
Pls make in Hindi Language

**Comment by arshadkazmi42** [comment]
@Sandeepkumarmadhdeshiya Hindi translation is in progress you can follow the progress here #168 

Beta site is here https://beta.hi.reactjs.org/learn/add-react-to-a-website

I will be closing this issue as we are tracking the translation progress at #168 

Feel free to reopen, if you have a different issue
