### ISSUE TITLE
Need a global tool

### ISSUE THREAD

**Issue by kambleaa007** [reactjs/hi.reactjs.org#37]
we need a global accepted open source tool which can convert English word to Hindi,
itself convertes filters words which need to be get converted or not,
it could save alot of time,
knowledge sharing between all contributors,
new beginners get attracted too,
it will make development fast and easy,
Not just for react conversion it could help to all different upcoming libraries, in future

**Comment by arshadkazmi42** [comment]
@kambleaa007 This is a really good idea. We can discuss more on going forward and build this tool.
> itself convertes filters words which need to be get converted or not,

I think this should be configurable

**Comment by saranshkataria** [comment]
Easier said than done. Many organizations provide translation services but none have been able to get it to work accurately. Hence the need for manual translations

**Comment by kambleaa007** [comment]
It's not easier but not impossible too,
We are providing open source free software to use.

**Comment by saranshkataria** [comment]
Feel free to start something if you think you should. Closing this issue out since it is not exactly relevant here.
