### ISSUE TITLE
The example's description having "TODO" translation can be improved

### ISSUE THREAD

**Issue by akanshgulati** [reactjs/hi.reactjs.org#38]
The current translation for "todo" in the example description seems little off from real definition. Tried to add the right work phonetically. 

**Current** -> टोडो
**Correct** -> टूडू

<img width="671" alt="Screenshot 2019-06-28 at 15 05 12" src="https://user-images.githubusercontent.com/5287100/60333377-76ef4280-99b6-11e9-82be-78ce88cf0132.png">

Shall I work on it and improve it?

**Comment by saranshkataria** [comment]
This occurs only in 1 instance, and yes, happy to accept a PR for it. Thanks for pointing that out. Also, there are a lot of pages that still need translation, so would love to see you contributing to those as well if you want to
