### ISSUE TITLE
using Text as it is , but it should be written in hindi 

### ISSUE THREAD

**Issue by AlokTakshak** [reactjs/hi.reactjs.org#48]
https://github.com/reactjs/hi.reactjs.org/blob/master/content/docs/rendering-elements.md

Here `Text` is used as it is but it should be written as `टेक्स्ट` according  to hindi glossary as decide in #2

**Comment by arshadkazmi42** [comment]
Good catch. 
Feel free to send a PR for this

**Comment by AlokTakshak** [comment]
sure

**Comment by AlokTakshak** [comment]
#49
