### ISSUE TITLE
Yarn dev not working

### ISSUE THREAD

**Issue by AlokTakshak** [reactjs/hi.reactjs.org#56]
When ever i am trying to start the project using `yarn dev` it throws the attached error

OS- Ubuntu 18.04
node- 10.16.3
yarn- 1.19.1

![Screenshot from 2019-10-17 09-38-54](https://user-images.githubusercontent.com/26347838/66977148-61676b00-f0c2-11e9-81d0-fd274a328c99.png)

**Comment by arshadkazmi42** [comment]
@AlokTakshak I am sure you would have done it. Just to be sure.
You have to run `yarn` first then `yarn dev`
Also, if you have ran `yarn` did you get any errors?
