### ISSUE TITLE
Noticed a bit of shift on the right hand side menu headings and the internal search bar in the React docs for hindi when compared to the original react docs.

### ISSUE THREAD

**Issue by bhatvikrant** [reactjs/hi.reactjs.org#81]
Please note that the internal Search bar and the headings in the right-hand sidebar are shifting a bit:
I am not sure if this is intentional. If it is please ignore. 🙂

![ezgif com-gif-maker](https://user-images.githubusercontent.com/50735025/88483350-e0100380-cf84-11ea-871c-94f6d1c65315.gif)

**Comment by saranshkataria** [comment]
This was because a commit adding margin upstream had not made it in the Hindi documentation yet. Usually the bot does that and it has a defined frequency of when to merge them, but I did it manually to verify it and they both match now. Thanks for the issue though.
