### ISSUE TITLE
Integrate CircleCI

### ISSUE THREAD

**Issue by arshadkazmi42** [reactjs/hi.reactjs.org#9]
Let's integrate Circle CI similar to Japanese translation repository

https://github.com/reactjs/ja.reactjs.org/tree/master/.circleci

**Comment by saranshkataria** [comment]
I did set it up using the website, but while adding it to the workflow, I don't see the option there. I guess it is a permission thing.

**Comment by saranshkataria** [comment]
Have integrated the check and set up the project on circle CI

**Comment by saranshkataria** [comment]
Tested working PR builds with #10, closing this out!
